// Code generated by Slice Machine. DO NOT EDIT.

import Contact from './Contact/index.svelte';
import FeaturedProject from './FeaturedProject/index.svelte';
import Hero from './Hero/index.svelte';
import Layout from './Layout/index.svelte';
import Process from './Process/index.svelte';
import Transition from './Transition/index.svelte';

export const components = {
	contact: Contact,
	featured_project: FeaturedProject,
	hero: Hero,
	layout: Layout,
	process: Process,
	transition: Transition
};
