// Code generated by Slice Machine. DO NOT EDIT.

import Contact from './Contact/index.svelte';
import FeaturedProject from './FeaturedProject/index.svelte';
import Hero from './Hero/index.svelte';
import Process from './Process/ProcessSlice.svelte';

export const components = {
	contact: Contact,
	featured_project: FeaturedProject,
	hero: Hero,
	process: Process
};
