// Code generated by Slice Machine. DO NOT EDIT.

import Project from './Project/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	project: Project,
	rich_text: RichText
};
