// Code generated by Slice Machine. DO NOT EDIT.

import Contact from './Contact/ContactSlice.svelte';
import FeaturedProject from './FeaturedProject/FeaturedProjectSlice.svelte';
import Hero from './Hero/HeroSlice.svelte';
import Process from './Process/ProcessSlice.svelte';
import Transition from './Transition/TransitionSlice.svelte';

export const components = {
	contact: Contact,
	featured_project: FeaturedProject,
	hero: Hero,
	process: Process,
	transition: Transition
};
