/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/avatar-winter.glb -o src/components/AvatarWinter.jsx -r public 
*/


import { useAnimations, useGLTF } from '@react-three/drei'
import { useControls } from 'leva'
import React, { useEffect, useRef } from 'react'

export function AvatarWinter(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/avatar-winter.glb')
  const { actions } = useAnimations(animations, group)
  const { animation } = useControls("ANIMATION", {
    animation: {
      value: "Idle",
      options: Object.keys(actions)
    }
  })

  useEffect(() => {
    actions[animation].reset().fadeIn(0.5).play()
    return () => actions[animation].fadeOut(0.5)
  }, [animation])
  console.log(actions)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Idle">
          <primitive object={nodes.Hips} />
          <skinnedMesh name="Wolf3D_Body002" geometry={nodes.Wolf3D_Body002.geometry} material={materials['Wolf3D_Body.002']} skeleton={nodes.Wolf3D_Body002.skeleton} />
          <skinnedMesh name="Wolf3D_Glasses002" geometry={nodes.Wolf3D_Glasses002.geometry} material={materials['Wolf3D_Glasses.002']} skeleton={nodes.Wolf3D_Glasses002.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Bottom002" geometry={nodes.Wolf3D_Outfit_Bottom002.geometry} material={materials['Wolf3D_Outfit_Bottom.002']} skeleton={nodes.Wolf3D_Outfit_Bottom002.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Footwear002" geometry={nodes.Wolf3D_Outfit_Footwear002.geometry} material={materials['Wolf3D_Outfit_Footwear.002']} skeleton={nodes.Wolf3D_Outfit_Footwear002.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Top002" geometry={nodes.Wolf3D_Outfit_Top002.geometry} material={materials['Wolf3D_Outfit_Top.002']} skeleton={nodes.Wolf3D_Outfit_Top002.skeleton} />
          <skinnedMesh name="EyeLeft002" geometry={nodes.EyeLeft002.geometry} material={materials['Wolf3D_Eye.002']} skeleton={nodes.EyeLeft002.skeleton} />
          <skinnedMesh name="EyeRight002" geometry={nodes.EyeRight002.geometry} material={materials['Wolf3D_Eye.002']} skeleton={nodes.EyeRight002.skeleton} />
          <skinnedMesh name="Wolf3D_Head002" geometry={nodes.Wolf3D_Head002.geometry} material={materials['Wolf3D_Skin.002']} skeleton={nodes.Wolf3D_Head002.skeleton} />
          <skinnedMesh name="Wolf3D_Teeth002" geometry={nodes.Wolf3D_Teeth002.geometry} material={materials['Wolf3D_Teeth.002']} skeleton={nodes.Wolf3D_Teeth002.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/avatar-winter.glb')
