/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/cat-midpoly.glb -o src/components/Cat.jsx -r public 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function Cat(props) {
  const { nodes, materials } = useGLTF('/models/cat-midpoly.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cat.geometry} material={materials.something} position={[-2.94, 0, -1.822]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/cat-midpoly.glb')
