/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/map.glb -o src/components/Models/Home.jsx -r public 
*/

import { useGLTF, useMatcapTexture } from '@react-three/drei';

export function Island(props) {
  const gltf = useGLTF('/models/map.glb');
  // gltf.castShadow = true;
  // gltf.scene.castShadow = true;
  const [blue] = useMatcapTexture('1D3FCC_051B5F_81A0F2_5579E9');
  const [satin] = useMatcapTexture('1B1B1B_999999_575757_747474');
  const [inverted] = useMatcapTexture('161B1F_C7E0EC_90A5B3_7B8C9B');
  return (
    <group
      {...props}
      dispose={null}
      scale={20}
    >
      <mesh
        receiveShadow
        castShadow
        geometry={gltf.nodes.Rock_2.geometry}
        material={gltf.materials.Rock}
        position={[-0.74, -0.039, -0.034]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={5}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={gltf.nodes.Icosphere.geometry}
        material={gltf.materials['Material.004']}
        position={[0, 0, -0.038]}
        rotation={[0, 0.641, 0]}
      >
        {/* <meshMatcapMaterial matcap={satin} /> */}
        <meshToonMaterial color={'#ffffff'} />
      </mesh>
      <mesh
        receiveShadow
        castShadow
        geometry={gltf.nodes.Plane.geometry}
        material={gltf.materials['Material.001']}
        position={[0, -0.009, 0]}
      >
        <meshMatcapMaterial matcap={inverted} />
      </mesh>
    </group>
  );
}

useGLTF.preload('/models/map.glb');
