/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../../public/models/map.glb --transform 
Files: ../../../public/models/map.glb [3.48MB] > /home/mandymozart/portfolio/src/components/Models/map-transformed.glb [68.11KB] (98%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/map-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock_2.geometry} material={materials.Rock} position={[-0.74, -0.039, -0.034]} rotation={[-Math.PI / 2, 0, 0]} scale={5} />
      <mesh geometry={nodes.Icosphere.geometry} material={materials['Material.004']} position={[0, 0, -0.038]} rotation={[0, 0.641, 0]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[0, -0.009, 0]} />
    </group>
  )
}

useGLTF.preload('/map-transformed.glb')
