/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../../public/models/mountain_and_river_scroll.glb -s --transform 
Files: ../../../public/models/mountain_and_river_scroll.glb [26.99MB] > /home/mandymozart/portfolio/src/components/Models/mountain_and_river_scroll-transformed.glb [1.84MB] (93%)
Author: Shahriar Shahrabi (https://sketchfab.com/shahriyarshahrabi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mountain-and-river-scroll-dd37769bdc0148a988535f893d01c551
Title: Mountain And River Scroll
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mountain_and_river_scroll-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane001_Material_0.geometry} material={materials.Material} position={[-101.376, 34.464, 9.399]} rotation={[-1.558, 0, 3.138]} scale={1.132} />
      <mesh castShadow receiveShadow geometry={nodes.Plane003_Material001_0.geometry} material={materials['Material.001']} position={[-100.162, 37.575, -37.556]} rotation={[-1.58, 0, Math.PI]} scale={0.708} />
      <mesh castShadow receiveShadow geometry={nodes.Accesories_VertexCollor_0.geometry} material={materials.VertexCollor} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Outline_VertexCollorBackFace_0.geometry} material={materials.VertexCollorBackFace} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Main_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/mountain_and_river_scroll-transformed.glb')
