/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../../public/models/radio-tower.glb --transform 
Files: ../../../public/models/radio-tower.glb [99.37KB] > /home/mandymozart/portfolio/src/components/Models/radio-tower-transformed.glb [11.46KB] (88%)
Author: kulioner (https://sketchfab.com/kulioner)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sm-radio-tower-by-google-poly-0b168196d835416d89d89302548273c1
Title: SM Radio Tower by Google Poly
*/

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

export function RadioTower(props) {
  const { nodes, materials } = useGLTF('/models/radio-tower-transformed.glb');
  const ref = useRef();
  return (
    <group
      position={[-45, 1, 30]}
      {...props}
      ref={ref}
      scale={[0.6, 0.6, 0.6]}
      theatreKey='RadioTower'
      dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.lambert2SG}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.lambert3SG}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.lambert4SG}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.lambert5SG}
        castShadow
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload('/models/radio-tower-transformed.glb');
