/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../../public/models/slide.glb --transform 
Files: ../../../public/models/slide.glb [75.18KB] > /home/mandymozart/portfolio/src/components/Models/slide-transformed.glb [6.49KB] (91%)
*/

import { useGLTF } from '@react-three/drei';
import React from 'react';
import useMenuStore from '../../stores/MenuStore';

export function Slide(props) {
  const { nodes, materials } = useGLTF('/models/slide-transformed.glb');
  const { colors } = useMenuStore();
  const materialControls = {
    color: colors.foreground,
    roughness: 0.4,
    metalness: 0.6,
    transmission: 0.2,
  };
  return (
    <group
      {...props}
      position={[0, 0, 0]}
      scale={[0.5, 0.5, 0.5]}
      theatreKey='Slide'
      dispose={null}>
      <mesh
        geometry={nodes.Circle.geometry}
        rotation={[-Math.PI / 2, 0, 0]}>
        <meshPhysicalMaterial
          side={2}
          {...materialControls}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('/models/slide-transformed.glb');
