/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../../public/models/trashbag.glb --transform 
Files: ../../../public/models/trashbag.glb [132.43KB] > /home/mandymozart/portfolio/src/components/Models/trashbag-transformed.glb [8.28KB] (94%)
*/

import { useGLTF } from '@react-three/drei';
import React from 'react';
import useMenuStore from '../../stores/MenuStore';

export function TrashBag(props) {
  const { ready } = useMenuStore();
  const { nodes, materials } = useGLTF('/models/trashbag.glb');
  return (
    <group
      {...props}
      dispose={null}>
      {ready && (
        <PositionalAudio
          url='/audio/wind-howl-interior.mp3'
          distance={1}
          loop
        />
      )}
      <pointLight
        intensity={20}
        color={0xffff00}
        position={[0, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere.geometry}
        material={materials.Black}
        position={[0.037, 0.663, -0.016]}
      />
    </group>
  );
}

useGLTF.preload('/models/trashbag.glb');
