/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../../public/models/trashbag.glb --transform 
Files: ../../../public/models/trashbag.glb [132.43KB] > /home/mandymozart/portfolio/src/components/Models/trashbag-transformed.glb [8.28KB] (94%)
*/

import { useGLTF } from '@react-three/drei';
import React from 'react';

export function TrashBag(props) {
  const { nodes, materials } = useGLTF('/models/trashbag.glb');
  return (
    <group
      {...props}
      dispose={null}>
      <mesh
        geometry={nodes.Icosphere.geometry}
        material={materials.Black}
        position={[0.037, 0.663, -0.016]}
      />
    </group>
  );
}

useGLTF.preload('/models/trashbag.glb');
